CREATE TABLE tag_config (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_name  TEXT        NOT NULL,
  display_name TEXT        NOT NULL,
  tag_type     CHAR(1)     NOT NULL,
  color        TEXT,
  description  TEXT,
  is_active    BOOLEAN,
  created_at   TIMESTAMPTZ,
  updated_at   TIMESTAMPTZ
);

CREATE TABLE client_tag (
  client_id    INT NOT NULL,
  ont_id       TEXT,
  tag_id       INT NOT NULL,
  assigned_at  TIMESTAMPTZ,
  assigned_by  TEXT,
  reason       TEXT,

  PRIMARY KEY (client_id, tag_id),

  FOREIGN KEY (tag_id) REFERENCES tag_config (id)
);

CREATE TABLE auto_tag_statistic (
  id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_id          INT         NOT NULL,
  assigned_count  INT         NOT NULL,
  run_started_at  TIMESTAMPTZ NOT NULL,
  run_finished_at TIMESTAMPTZ NOT NULL,

  FOREIGN KEY (tag_id) REFERENCES tag_config (id)
);
